"""eliminar sectores y ubicacion

Revision ID: 099246a3643f
Revises: b7e3f0a1c9d2
Create Date: 2026-07-24 11:33:18.093055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '099246a3643f'
down_revision: Union[str, Sequence[str], None] = 'b7e3f0a1c9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sectores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sectores_id'))

    op.drop_table('sectores')
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.drop_column('ubicacion')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion', sa.VARCHAR(length=200), nullable=True))

    op.create_table('sectores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), nullable=False),
    sa.Column('activo', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sectores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sectores_id'), ['id'], unique=False)

    # ### end Alembic commands ###
