"""sectores

Revision ID: 5d588dc90276
Revises: d6f7dc049efc
Create Date: 2026-07-23 20:14:13.282556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d588dc90276'
down_revision: Union[str, Sequence[str], None] = 'd6f7dc049efc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sectores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sectores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sectores_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sectores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sectores_id'))

    op.drop_table('sectores')
    # ### end Alembic commands ###
