"""sena, fecha_prometida, ajustes y express en ordenes

Revision ID: 9a71d7da52bd
Revises: 099246a3643f
Create Date: 2026-07-24 12:00:19.488456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a71d7da52bd'
down_revision: Union[str, Sequence[str], None] = '099246a3643f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('express', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('descuento', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('recargo', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('ajuste_motivo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('monto_pagado', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('fecha_prometida', sa.Date(), nullable=True))

    # ### end Alembic commands ###

    # Backfill: los pedidos ya marcados como pagados quedan con el total abonado.
    op.execute("UPDATE ordenes SET monto_pagado = total WHERE pagado")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ordenes', schema=None) as batch_op:
        batch_op.drop_column('fecha_prometida')
        batch_op.drop_column('monto_pagado')
        batch_op.drop_column('ajuste_motivo')
        batch_op.drop_column('recargo')
        batch_op.drop_column('descuento')
        batch_op.drop_column('express')

    # ### end Alembic commands ###
